### ISSUE TITLE
cannot work in Github Action env

### ISSUE THREAD

**Issue by begoat** [brandonocasey/karma-safari-applescript-launcher#5]
Hi @brandonocasey , Thanks for this awesome libs.
It works on my local machine(10.14.6)

But I want to use it in `Github Action` env, it failed.

Here are the logs.
```
[karam-test:singlerun] 07 04 2020 00:32:46.389:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
[karam-test:singlerun] 07 04 2020 00:32:46.389:INFO [launcher]: Launching browsers Safari with concurrency unlimited
[karam-test:singlerun] 07 04 2020 00:32:46.403:INFO [launcher]: Starting browser Safari
[karam-test:singlerun] 07 04 2020 00:32:46.403:DEBUG [launcher]: null -> BEING_CAPTURED
[karam-test:singlerun] 07 04 2020 00:32:46.404:DEBUG [temp-dir]: Creating temp dir at /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/karma-97775348
[karam-test:singlerun] ee
[karam-test:singlerun] 07 04 2020 00:34:48.361:ERROR [karma-server]: UncaughtException
[karam-test:singlerun] 07 04 2020 00:34:48.362:DEBUG [launcher]: Disconnecting all browsers
[karam-test:singlerun] 07 04 2020 00:34:48.370:DEBUG [launcher]: BEING_CAPTURED -> BEING_KILLED
[karam-test:singlerun] 07 04 2020 00:34:48.371:DEBUG [launcher]: BEING_KILLED -> BEING_FORCE_KILLED
[karam-test:singlerun] ee
[karam-test:singlerun] 07 04 2020 00:36:48.711:ERROR [karma-server]: UncaughtException
[karam-test:singlerun] 07 04 2020 00:36:48.712:DEBUG [launcher]: Disconnecting all browsers
[karam-test:singlerun] 07 04 2020 00:36:48.712:DEBUG [launcher]: BEING_FORCE_KILLED -> BEING_FORCE_KILLED
[karam-test:singlerun] 07 04 2020 00:36:48.712:DEBUG [launcher]: BEING_FORCE_KILLED -> FINISHED
[karam-test:singlerun] npm ERR! code ELIFECYCLE
```

here is my <code>karma.config.js</code>
```
    plugins: ['karma-*', 'karma-safari-applescript-launcher'],

    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    // browsers: ['ChromeHeadlessCustom'],
    browsers: ['Safari'],
```

here is my github action.yaml
```
  run-on-safari:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
      fail-fast:
        false
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn --frozen-lockfile

    - run: yarn run test
```
```
